## Travel network analysis for infectious disease transmission in Pacific Island countries

In [1]:
import numpy as np

### 1.Model

### 2.Migration Step

In [19]:
import numpy as np

Tmax = 365  # Simulation days
D = 6  # Number of locations
L = 2  # Number of external connections

population = np.array([1200, 800, 1500, 1000, 2000])

# Initialize the state vector array, where each position's state vector is a 4-dimensional vector [S, E, I, R]
vectors = np.zeros((D, 4))

# Define the migration matrix W, representing the migration between each pair of locations, where each element is a 4-dimensional vector [S, E, I, R]
migration_matrix = np.random.randint(1, 5, size=(D, D, 4))

# Set the diagonal elements (migration within the same location) to 0
for i in range(D):
    migration_matrix[i, i, :] = 0

# Ensure that the total migration in and out of each location is the same
migration_totals = np.sum(migration_matrix, axis=2, keepdims=True)
migration_totals[migration_totals == 0] = 1  # Avoid division by zero errors
migration_matrix = migration_matrix / migration_totals

# Output initial state
print("Initial state:")
for i, vector in enumerate(vectors):
    print(f"Location {i + 1}: {vector}")

# Print the migration matrix W
print("\nMigration matrix W:")
print(migration_matrix)



Initial state:
Location 1: [0. 0. 0. 0.]
Location 2: [0. 0. 0. 0.]
Location 3: [0. 0. 0. 0.]
Location 4: [0. 0. 0. 0.]
Location 5: [0. 0. 0. 0.]
Location 6: [0. 0. 0. 0.]

Migration matrix W:
[[[0.         0.         0.         0.        ]
  [0.28571429 0.28571429 0.14285714 0.28571429]
  [0.33333333 0.25       0.16666667 0.25      ]
  [0.5        0.25       0.125      0.125     ]
  [0.27272727 0.18181818 0.36363636 0.18181818]
  [0.18181818 0.27272727 0.27272727 0.27272727]]

 [[0.125      0.25       0.375      0.25      ]
  [0.         0.         0.         0.        ]
  [0.33333333 0.33333333 0.25       0.08333333]
  [0.3        0.3        0.1        0.3       ]
  [0.3        0.2        0.3        0.2       ]
  [0.1        0.3        0.2        0.4       ]]

 [[0.36363636 0.09090909 0.27272727 0.27272727]
  [0.16666667 0.16666667 0.16666667 0.5       ]
  [0.         0.         0.         0.        ]
  [0.25       0.125      0.25       0.375     ]
  [0.1        0.4        0.4        

### 3.Infection Step